import * as fs from "fs";
import * as path from "path";

/**
 * Export Contract ABIs Script
 * 
 * This script extracts ABIs from compiled Hardhat artifacts and generates
 * a TypeScript file for use in the Next.js frontend.
 * 
 * Usage:
 *   ts-node scripts/export-abis.ts
 *   or
 *   pnpm export:abis
 */

interface ContractArtifact {
    abi: any[];
    contractName: string;
}

async function main() {
    console.log("\n📦 Exporting Contract ABIs...\n");

    // Paths
    const artifactsDir = path.join(__dirname, "..", "artifacts", "contracts");
    const frontendDir = path.join(__dirname, "..", "..", "nextjs", "src", "contracts");
    const outputFile = path.join(frontendDir, "contractABIs.ts");

    // Contract paths
    const factoryArtifactPath = path.join(
        artifactsDir,
        "LotteryFactory.sol",
        "LotteryFactory.json"
    );
    const lotteryArtifactPath = path.join(
        artifactsDir,
        "ZadictionLottery.sol",
        "ZadictionLottery.json"
    );

    // Check if artifacts exist
    if (!fs.existsSync(factoryArtifactPath)) {
        console.error("❌ LotteryFactory artifact not found!");
        console.error("   Please run: pnpm contracts:build");
        process.exit(1);
    }

    if (!fs.existsSync(lotteryArtifactPath)) {
        console.error("❌ ZadictionLottery artifact not found!");
        console.error("   Please run: pnpm contracts:build");
        process.exit(1);
    }

    // Read artifacts
    console.log("📖 Reading contract artifacts...");
    const factoryArtifact: ContractArtifact = JSON.parse(
        fs.readFileSync(factoryArtifactPath, "utf-8")
    );
    const lotteryArtifact: ContractArtifact = JSON.parse(
        fs.readFileSync(lotteryArtifactPath, "utf-8")
    );

    console.log("✅ Factory ABI loaded");
    console.log("✅ Lottery ABI loaded");

    // Generate TypeScript content
    console.log("\n🔨 Generating TypeScript file...");

    const tsContent = `/**
 * Auto-generated Contract ABIs
 * 
 * This file is automatically generated from compiled Hardhat artifacts.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * 
 * To regenerate: pnpm --filter ./packages/hardhat export:abis
 * 
 * Generated: ${new Date().toISOString()}
 */

// ============================================
// FACTORY CONTRACT ABI
// ============================================

export const FACTORY_ABI = ${JSON.stringify(factoryArtifact.abi, null, 2)} as const;

// Human-readable format for ethers.js Interface
export const FACTORY_ABI_HUMAN = [
  "function createMarket(uint8 _digits, uint256 _betPeriod, uint256 _initialOdds, uint256 _minOdds, uint256 _creatorFeePercent) external payable returns (address)",
  "function getAllMarkets() external view returns (address[])",
  "function getMarketInfo(address _market) external view returns (address, uint256, uint8, uint256, uint256, uint256, bool, bool)",
  "function owner() external view returns (address)",
  "function protocolFeePercent() external view returns (uint256)",
  "event MarketCreated(address indexed marketAddress, address indexed owner, uint256 roundId)"
] as const;

// ============================================
// LOTTERY/MARKET CONTRACT ABI
// ============================================

export const MARKET_ABI = ${JSON.stringify(lotteryArtifact.abi, null, 2)} as const;

// Human-readable format for ethers.js Interface
export const MARKET_ABI_HUMAN = [
  // View Functions - Contract Info
  "function creator() external view returns (address)",
  "function owner() external view returns (address)",
  "function roundId() external view returns (uint256)",
  "function digits() external view returns (uint8)",
  "function maxNumber() external view returns (uint256)",
  "function betDeadline() external view returns (uint256)",
  "function collateral() external view returns (uint256)",
  "function liabilityLimit() external view returns (uint256)",
  "function initialOdds() external view returns (uint256)",
  "function minOdds() external view returns (uint256)",
  "function feePercent() external view returns (uint256)",
  "function creatorFeePercent() external view returns (uint256)",
  "function protocolFeePercent() external view returns (uint256)",
  "function exposure(uint256) external view returns (uint256)",
  "function totalStakes(uint256) external view returns (uint256)",
  "function isResolved() external view returns (bool)",
  "function winningNumber() external view returns (uint256)",
  "function totalUnclaimedPayouts() external view returns (uint256)",
  "function drawRequestedAt() external view returns (uint256)",
  "function getBetCount() external view returns (uint256)",
  "function bets(uint256) external view returns (address player, uint256 number, uint256 amount, uint256 lockedOdds, uint256 potentialPayout, bool claimed)",
  "function getOdds(uint256 number, uint256 amount) external view returns (uint256)",
  "function maxBet(uint256 number) external view returns (uint256)",
  "function getUserBets(address user) external view returns (tuple(address player, uint256 number, uint256 amount, uint256 lockedOdds, uint256 potentialPayout, bool claimed)[])",
  
  // Write Functions
  "function placeBet(uint256 number) external payable",
  "function drawResult() external",
  "function claimWinnings() external",
  "function withdrawCollateral() external",
  
  // Events
  "event BetPlaced(address indexed player, uint256 number, uint256 amount, uint256 odds, uint256 potentialPayout)",
  "event DrawRequested(uint256 timestamp)",
  "event RoundResolved(uint256 winningNumber)",
  "event WinningsClaimed(address indexed player, uint256 amount)",
  "event CollateralWithdrawn(address indexed owner, uint256 amount)"
] as const;

// ============================================
// TYPE EXPORTS
// ============================================

export type FactoryABI = typeof FACTORY_ABI;
export type MarketABI = typeof MARKET_ABI;
`;

    // Ensure output directory exists
    if (!fs.existsSync(frontendDir)) {
        fs.mkdirSync(frontendDir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(outputFile, tsContent, "utf-8");
    console.log("✅ TypeScript file generated");

    // Summary
    console.log("\n📋 Export Summary:");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("Output file:       ", path.relative(process.cwd(), outputFile));
    console.log("Factory functions: ", factoryArtifact.abi.filter((x: any) => x.type === "function").length);
    console.log("Lottery functions: ", lotteryArtifact.abi.filter((x: any) => x.type === "function").length);
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    console.log("\n✨ ABIs exported successfully!\n");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("\n❌ Export failed:");
        console.error(error);
        process.exit(1);
    });
